cdef int XOR_A_B(GBCPU cpu)
cdef int XOR_A_C(GBCPU cpu)
cdef int XOR_A_D(GBCPU cpu)
cdef int XOR_A_E(GBCPU cpu)
cdef int XOR_A_H(GBCPU cpu)
cdef int XOR_A_L(GBCPU cpu)
cdef int XOR_A_A(GBCPU cpu)
cdef int XOR_A_HL(GBCPU cpu)
