cdef int LD_B_u8(GBCPU cpu)
cdef int LD_C_u8(GBCPU cpu)
cdef int LD_D_u8(GBCPU cpu)
cdef int LD_E_u8(GBCPU cpu)
cdef int LD_H_u8(GBCPU cpu)
cdef int LD_L_u8(GBCPU cpu)
cdef int LD_A_u8(GBCPU cpu)
cdef int LD_HL_u8(GBCPU cpu)
